### ISSUE TITLE
wwivd service getting killed

### ISSUE THREAD

**Issue by granitepenguin** [wwivbbs/wwiv#1003]
OS: Linux debian 8
Build: 2480

I've noticed a couple times now that the wwivd service has failed

```
root@vps40748:~# systemctl status wwivd -l
* wwivd.service - wwivd: WWIV UNIX Daemon
   Loaded: loaded (/etc/systemd/system/wwivd.service; enabled)
   Active: failed (Result: signal) since Sun 2017-02-05 23:15:15 CST; 10h ago
  Process: 17741 ExecStart=/bbs/wwiv/wwivd $VERBOSE (code=killed, signal=SEGV)
 Main PID: 17741 (code=killed, signal=SEGV)

Feb 05 23:02:27 foobar wwivd[17741]: ~RemoteSocketIO2017-02-05 23:02:27,027 INFO  [17741] Node #2 exited with error code: 0
Feb 05 23:15:09 foobar wwivd[17741]: 2017-02-05 23:15:09,919 INFO  Nodes in use: (0/5)
Feb 05 23:15:09 foobar wwivd[17741]: 2017-02-05 23:15:09,924 INFO  Connection from: 179.255.156.4
Feb 05 23:15:09 foobar wwivd[17741]: 2017-02-05 23:15:09,929 INFO  [17741] Invoking Command Line (posix_spawn):./bbs -XT -H7 -N2
Feb 05 23:15:13 foobar wwivd[17741]: 2017-02-05 23:15:13,582 INFO  Trashcan name entered from IP: 179.255.156.4; name: USER
Feb 05 23:15:14 foobar wwivd[17741]: ~RemoteSocketIO2017-02-05 23:15:14,513 INFO  [17741] Node #2 exited with error code: 0
Feb 05 23:15:15 foobar wwivd[17741]: 2017-02-05 23:15:15,457 INFO  Nodes in use: (0/5)Connection from: 179.255.156.4
Feb 05 23:15:15 foobar wwivd[17741]: 2017-02-05 23:15:15,466 INFO  [17741] Invoking Command Line (posix_spawn):./bbs -XT -H7 -N2
Feb 05 23:15:15 foobar systemd[1]: wwivd.service: main process exited, code=killed, status=11/SEGV
Feb 05 23:15:15 foobar systemd[1]: Unit wwivd.service entered failed state.
```

**Comment by wwiv** [comment]
do you have a core? if so can you get a bt?

**Comment by granitepenguin** [comment]
no, I don't.  I'll have to see if I can set the system up to dump a core if it happens again.

**Comment by granitepenguin** [comment]
upped the verbosity of the wwivd service, didn't get much more out of it

```
systemd[1]: Starting wwivd: WWIV UNIX Daemon... 
systemd[1]: Failed to reset devices.list on /system.slice/wwivd.service: No such file or directory
systemd[1]: Started wwivd: WWIV UNIX Daemon.
wwivd[10596]: 2017-02-12 12:32:54,782 INFO  wwivd - WWIV Daemon.
wwivd[10596]: 2017-02-12 12:32:54,785 VER-2 Using WWIV_DIR: /bbs/wwiv
wwivd[10596]: 2017-02-12 12:32:54,787 VER-2 Using WWIV_USER(1): wwiv
wwivd[10596]: 2017-02-12 12:32:54,790 VER-2 Using WWIV_USER: wwiv
wwivd[10596]: 2017-02-12 12:32:54,792 VER-3 SH_OPEN /bbs/wwiv/config.dat, access=0
wwivd[10596]: 2017-02-12 12:32:54,794 VER-3 SH_OPEN /bbs/wwiv/config.dat, access=0, handle=4
wwivd[10596]: 2017-02-12 12:32:54,797 VER-3 CLOSE /bbs/wwiv/config.dat, handle=4
wwivd[10596]: 2017-02-12 12:32:54,800 INFO  Listening to TELNET on port: 23
wwivd[10596]: 2017-02-12 12:32:54,802 INFO  Listening to SSH on port: 2222
wwivd[10596]: 2017-02-12 12:32:54,805 INFO  Listening to BINKP on port: 24554
wwivd[10596]: 2017-02-12 12:32:54,807 INFO  Listening to HTTP on port: 8080
wwivd[10596]: 2017-02-12 12:32:54,811 INFO  Nodes in use: (0/5)
wwivd[10596]: 2017-02-12 12:32:54,814 VER-1 About to call select. (7)
wwivd[10596]: 2017-02-12 12:32:58,764 VER-1 After select.
wwivd[10596]: 2017-02-12 12:32:58,885 INFO  Accepted connection on port: 23; from: 27.27.211.89; coutry code: 0
wwivd[10596]: 2017-02-12 12:32:58,886 INFO  Nodes in use: (0/5)
wwivd[10596]: 2017-02-12 12:32:58,886 VER-1 About to call select. (7)
wwivd[10596]: 2017-02-12 12:32:58,893 VER-1 [10596] launch_node(2)
wwivd[10596]: 2017-02-12 12:32:58,898 VER-3 SH_OPEN /bbs/wwiv/data/nodeinuse.2, access=578
wwivd[10596]: 2017-02-12 12:32:58,904 VER-3 SH_OPEN /bbs/wwiv/data/nodeinuse.2, access=578, handle=9
wwivd[10596]: 2017-02-12 12:32:58,909 VER-3 CLOSE /bbs/wwiv/data/nodeinuse.2, handle=9
systemd[1]: wwivd.service: main process exited, code=killed, status=11/SEGV 
systemd[1]: Unit wwivd.service entered failed state. 
```

Still working on getting core dumping to work.  Might need to rebuild on a different system to get that to work.

**Comment by granitepenguin** [comment]
yeah, on build 2505 now and anything that touches wwivd is causing a crash; telnet, ssh, binkp, http.  Doesn't matter which.

**Comment by granitepenguin** [comment]
ok, looks like it's related to when wwivd is running under systemd.  If I run wwivd on the command line directly, it's not crashing.

**Comment by wwiv** [comment]
even running it as the systemd service, it's not crashing for me

**Comment by granitepenguin** [comment]
Ok, managed to get a bt

```gdb
root@vps40748:/bbs/wwiv# gdb wwivd
GNU gdb (Debian 7.7.1+dfsg-5) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from wwivd...done.
run(gdb) run
Starting program: /bbs/wwiv/wwivd
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
2017-02-12 18:27:25,354 INFO  wwivd - WWIV Daemon.
2017-02-12 18:27:25,356 INFO  Listening to TELNET on port: 2323
2017-02-12 18:27:25,358 INFO  Listening to SSH on port: 2222
2017-02-12 18:27:25,358 INFO  Listening to BINKP on port: 24554
2017-02-12 18:27:25,358 INFO  Listening to HTTP on port: 8080
2017-02-12 18:27:25,492 ERROR Unable to find uid for username: wwiv2
2017-02-12 18:27:25,492 INFO  Nodes in use: (0/5)
2017-02-12 18:28:04,189 INFO  Accepted connection on port: 2222; from: 71.201.51.130; coutry code: 0
[New Thread 0x7ffff619a700 (LWP 8533)]
2017-02-12 18:28:04,213 INFO  Nodes in use: (0/5)

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff619a700 (LWP 8533)]
__memcpy_sse2_unaligned ()
    at ../sysdeps/x86_64/multiarch/memcpy-sse2-unaligned.S:36
36      ../sysdeps/x86_64/multiarch/memcpy-sse2-unaligned.S: No such file or directory.
(gdb) bt
#0  __memcpy_sse2_unaligned ()
    at ../sysdeps/x86_64/multiarch/memcpy-sse2-unaligned.S:36
#1  0x00007ffff7953d4b in std::basic_streambuf<char, std::char_traits<char> >::xsputn(char const*, long) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#2  0x00007ffff794b316 in std::basic_ostream<char, std::char_traits<char> >& std::__ostream_insert<char, std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, char const*, long) ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00000000004cfeea in wwiv::strings::StrCat<std::string> (
    a="%msg\000time\000\066\000\060\000\000\000A\000\000\000\000\000\000\000/lib/x86_64-linux-gnu/libnss_myhostname.so.2", '\000' <repeats 12 times>, "A\000\000\000\000\000\000\000/lib/x86_64-linux-gnu\000libnss_myhostname.so.2\000\000\000\000    B\000\000\000A\000\000\000\000\000\000\000`²v\000\000\000\000\000╨\031 ≈ \177\000\000°┘ ≈ \177\000\000\000\000\000\000\000\000\000\000`²v\000\000\000\000\000╨\031 ≈ \177\000\000"...) at /bbs/build/wwiv/wwivd/../core/strings.h:39
#4  0x00000000004cb146 in wwiv::strings::StrCat<char [12], std::string> (a=...)
    at /bbs/build/wwiv/wwivd/../core/strings.h:46
#5  0x00000000004b7b52 in launch_node (config=..., c=...,
    nodes=0x7fffffffe360, node_number=2, sock=8, connection_type=SSH,
    remote_peer="%msg\000time\000\066\000\060\000\000\000A\000\000\000\000\000\000\000/lib/x86_64-linux-gnu/libnss_myhostname.so.2", '\000' <repeats 12 times>, "A\000\000\000\000\000\000\000/lib/x86_64-linux-gnu\000libnss_myhostname.so.2\000\000\000\000    B\000\000\000A\000\000\000\000\000\000\000`²v\000\000\000\000\000╨\031 ≈ \177\000\000°┘ ≈ \177\000\000\000\000\000\000\000\000\000\000`²v\000\000\000\000\000╨\031 ≈ \177\000\000"...) at /bbs/build/wwiv/wwivd/wwivd.cpp:492
#6  0x00000000004b84ac in HandleAccept (config=..., c=...,
    nodes=0x7fffffffe360, r=...,
---Type <return> to continue, or q <return> to quit---
    remote_peer="%msg\000time\000\066\000\060\000\000\000A\000\000\000\000\000\000\000/lib/x86_64-linux-gnu/libnss_myhostname.so.2", '\000' <repeats 12 times>, "A
\000\000\000\000\000\000\000/lib/x86_64-linux-gnu\000libnss_myhostname.so.2\000\000\000\000    B\000\000\000A\000\000\000\000\000\000\000`²v\000\000\000\000\000╨\
031 ≈ \177\000\000°┘ ≈ \177\000\000\000\000\000\000\000\000\000\000`²v\000\0
00\000\000\000╨\031 ≈ \177\000\000"...) at /bbs/build/wwiv/wwivd/wwivd.cpp:560
#7  0x00000000004e800c in std::_Bind_simple<void (*(std::reference_wrapper<wwiv:
:sdk::Config const>, std::reference_wrapper<wwivd_config_t const>, NodeManager*,
 wwiv::core::accepted_socket_t, std::reference_wrapper<std::string>))(wwiv::sdk:
:Config const&, wwivd_config_t const&, NodeManager*, wwiv::core::accepted_socket
_t, std::string const&)>::_M_invoke<0ul, 1ul, 2ul, 3ul, 4ul>(std::_Index_tuple<0
ul, 1ul, 2ul, 3ul, 4ul>) (this=0x76fc88)
    at /usr/include/c++/4.9/functional:1700
#8  0x00000000004e7ca1 in std::_Bind_simple<void (*(std::reference_wrapper<wwiv:
:sdk::Config const>, std::reference_wrapper<wwivd_config_t const>, NodeManager*,
 wwiv::core::accepted_socket_t, std::reference_wrapper<std::string>))(wwiv::sdk:
:Config const&, wwivd_config_t const&, NodeManager*, wwiv::core::accepted_socket
_t, std::string const&)>::operator()() (this=0x76fc88)
    at /usr/include/c++/4.9/functional:1688
#9  0x00000000004e79ea in std::thread::_Impl<std::_Bind_simple<void (*(std::refe
rence_wrapper<wwiv::sdk::Config const>, std::reference_wrapper<wwivd_config_t co
nst>, NodeManager*, wwiv::core::accepted_socket_t, std::reference_wrapper<std::s
tring>))(wwiv::sdk::Config const&, wwivd_config_t const&, NodeManager*, wwiv::co
re::accepted_socket_t, std::string const&)> >::_M_run() (this=0x76fc70)
    at /usr/include/c++/4.9/thread:115
#10 0x00007ffff796a970 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#11 0x00007ffff7bc70a4 in start_thread (arg=0x7ffff619a700)
---Type <return> to continue, or q <return> to quit---
    at pthread_create.c:309
#12 0x00007ffff70da62d in clone ()
    at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
(gdb)
```

**Comment by granitepenguin** [comment]
Currently running build 2511, and looks a lot better.  Going to run it for a while and see if it holds up.

**Comment by wwiv** [comment]
I think I fixed the problems from the string reference, completely now since I don't pass it in but rather create it in the thread.

feel free to reopen or log a new issue for other crashes
