### ISSUE TITLE
wfc and wwivd failing to run

### ISSUE THREAD

**Issue by granitepenguin** [wwivbbs/wwiv#1126]
OS Debian 9
WWIV anything higher than 2753

The latest builds are not running.  If I try to start ./bbs, I'm getting an endless loop of this:

```
terminate called after throwing an instance of 'std::out_of_range'
  what():  map::at
Aborted
```
and I'm seeing the same thing in the wwivd logs:

```
Jul 03 16:20:58 beaglebbs wwivd[27155]: terminate called after throwing an instance of 'terminate called after throwing an instance of 'std::out_of_range'
Jul 03 16:20:58 beaglebbs wwivd[27155]:   what():  map::at
Jul 03 16:20:58 beaglebbs wwivd[27155]: Aborted
```

**Comment by granitepenguin** [comment]
tried getting a bt, but it's not actually faulting; it's just failing and constantly restarting.  This is what I see when I ^C it

```gdb
^C
Program received signal SIGINT, Interrupt.
0x00007ffff6cd2aea in __waitpid (pid=28678, stat_loc=0x7fffffffa1a4, options=0)
    at ../sysdeps/unix/sysv/linux/waitpid.c:29
29      ../sysdeps/unix/sysv/linux/waitpid.c: No such file or directory.
(gdb) bt
#0  0x00007ffff6cd2aea in __waitpid (pid=28678, stat_loc=0x7fffffffa1a4,
    options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:29
#1  0x00005555558b1f61 in UnixSpawn (cmd="/bbs/wwiv/network1 .0", environ=0x0,
    flags=128) at /bbs/git/wwiv/bbs/platform/unix/exec.cpp:53
#2  0x00005555558b207a in ExecExternalProgram (
    cmdline="/bbs/wwiv/network1 .0", flags=128)
    at /bbs/git/wwiv/bbs/platform/unix/exec.cpp:78
#3  0x0000555555793375 in ExecuteExternalProgram (
    commandLine="/bbs/wwiv/network1 .0", nFlags=128)
    at /bbs/git/wwiv/bbs/execexternal.cpp:65
#4  0x00005555557f6874 in cleanup_net1 () at /bbs/git/wwiv/bbs/netsup.cpp:198
#5  0x00005555557f6cf8 in cleanup_net () at /bbs/git/wwiv/bbs/netsup.cpp:241
#6  0x00005555558a1509 in Application::InitializeBBS (this=0x555555e3e0b0)
    at /bbs/git/wwiv/bbs/xinit.cpp:798
#7  0x000055555575c01c in Application::Run (this=0x555555e3e0b0, argc=1,
    argv=0x7fffffffed08) at /bbs/git/wwiv/bbs/application.cpp:917
#8  0x0000555555756652 in bbsmain (argc=1, argv=0x7fffffffed08)
    at /bbs/git/wwiv/bbs/bbs.cpp:91
#9  0x0000555555756560 in main (argc=1, argv=0x7fffffffed08)
    at /bbs/git/wwiv/bbs/bbs_main.cpp:22
(gdb)
```

looks like it might be related to network1 rolling over.

**Comment by granitepenguin** [comment]
trying to capture a ^C again

```gdb
^C
Program received signal SIGINT, Interrupt.
0x00007ffff69db38b in __libc_fork () at ../sysdeps/nptl/fork.c:135
135     ../sysdeps/nptl/fork.c: No such file or directory.
(gdb) terminate called after throwing an instance of 'std::out_of_range'
  what():  map::at
Aborted
bt
#0  0x00007ffff69db38b in __libc_fork () at ../sysdeps/nptl/fork.c:135
#1  0x00005555558b1e9a in UnixSpawn (cmd="/bbs/wwiv/network1 .0", environ=0x0,
    flags=128) at /bbs/git/wwiv/bbs/platform/unix/exec.cpp:33
#2  0x00005555558b207a in ExecExternalProgram (
    cmdline="/bbs/wwiv/network1 .0", flags=128)
    at /bbs/git/wwiv/bbs/platform/unix/exec.cpp:78
#3  0x0000555555793375 in ExecuteExternalProgram (
    commandLine="/bbs/wwiv/network1 .0", nFlags=128)
    at /bbs/git/wwiv/bbs/execexternal.cpp:65
#4  0x00005555557f6874 in cleanup_net1 () at /bbs/git/wwiv/bbs/netsup.cpp:198
#5  0x00005555557f6cf8 in cleanup_net () at /bbs/git/wwiv/bbs/netsup.cpp:241
#6  0x00005555558a1509 in Application::InitializeBBS (this=0x555555e3e0b0)
    at /bbs/git/wwiv/bbs/xinit.cpp:798
#7  0x000055555575c01c in Application::Run (this=0x555555e3e0b0, argc=1,
    argv=0x7fffffffed08) at /bbs/git/wwiv/bbs/application.cpp:917
#8  0x0000555555756652 in bbsmain (argc=1, argv=0x7fffffffed08)
    at /bbs/git/wwiv/bbs/bbs.cpp:91
#9  0x0000555555756560 in main (argc=1, argv=0x7fffffffed08)
    at /bbs/git/wwiv/bbs/bbs_main.cpp:22
(gdb)
```

**Comment by granitepenguin** [comment]
yup, it's in network1

```gdb
wwiv@beaglebbs:~$ gdb --args ./network1 .0
GNU gdb (Debian 7.12-6) 7.12.0.20161007-git
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./network1...done.
(gdb) run
Starting program: /bbs/wwiv/network1 .0
terminate called after throwing an instance of 'std::out_of_range'
  what():  map::at

Program received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff71d142a in __GI_abort () at abort.c:89
#2  0x00007ffff7ae80ad in __gnu_cxx::__verbose_terminate_handler() ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007ffff7ae6066 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007ffff7ae60b1 in std::terminate() ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ffff7ae62c9 in __cxa_throw ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007ffff7b0ea6f in std::__throw_out_of_range(char const*) ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#7  0x0000555555623637 in std::map<std::__cxx11::basic_string<char, std::char_traits<char>, 
std::allocator<char> > const, wwiv::core::CommandLineArgument, 
std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const>, 
std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > 
const, wwiv::core::CommandLineArgument> >
>::at (this=0x7fffffffd7a0, __k="xxxx")
    at /usr/include/c++/6/bits/stl_map.h:523
#8  0x00005555556205c0 in wwiv::core::CommandLineCommand::HandleCommandLineArgument (this=0x7fffffffd780, key="xxxx", value="0")
    at /bbs/git/wwiv/core/command_line.cpp:125
#9  0x000055555562118a in wwiv::core::CommandLineCommand::Parse (
    this=0x7fffffffd780, start_pos=1)
    at /bbs/git/wwiv/core/command_line.cpp:186
#10 0x0000555555620452 in wwiv::core::CommandLine::ParseImpl (
    this=0x7fffffffd780) at /bbs/git/wwiv/core/command_line.cpp:107
#11 0x0000555555620239 in wwiv::core::CommandLine::Parse (this=0x7fffffffd780)
    at /bbs/git/wwiv/core/command_line.cpp:87
#12 0x000055555562fee9 in wwiv::core::Logger::Init (argc=2,
    argv=0x7fffffffecf8, c=...) at /bbs/git/wwiv/core/log.cpp:154
#13 0x000055555562fdb5 in wwiv::core::Logger::Init (argc=2,
    argv=0x7fffffffecf8) at /bbs/git/wwiv/core/log.cpp:143
#14 0x00005555556110a6 in network1_main (argc=2, argv=0x7fffffffecf8)
    at /bbs/git/wwiv/network1/network1.cpp:156
#15 0x00005555556117ba in main (argc=2, argv=0x7fffffffecf8)
    at /bbs/git/wwiv/network1/network1.cpp:193
(gdb)
```

**Comment by granitepenguin** [comment]
Looks good here
