### ISSUE TITLE
WFC failing to start

### ISSUE THREAD

**Issue by granitepenguin** [wwivbbs/wwiv#1131]
OS: linux
WWIV: 2777

WFC is getting an error on startup

```gdb
Program received signal SIGFPE, Arithmetic exception.     
0x0000555555802138 in std::chrono::operator/<long, std::ratio<3600l, 1l>, unsigned char> (__d=..., __s=@0x555555e69828: 0 '\000')
                  at /usr/include/c++/6/chrono:434                                            434             return __cd(__cd(__d).count() / __s);                           
(gdb) bt                                                                        
#0  0x0000555555802138 in std::chrono::operator/<long, std::ratio<3600l, 1l>, unsigned char> (__d=..., __s=@0x555555e69828: 0 '\000')                               at /usr/include/c++/6/chrono:434                                            
#1  0x00005555557fc0d1 in ok_to_call_from_contact_rec (ncn=..., con=...)            at /bbs/git/wwiv/bbs/netsup.cpp:389                                         
#2  0x00005555557fc538 in attempt_callout ()                                        at /bbs/git/wwiv/bbs/netsup.cpp:437                                         
#3  0x00005555558b3144 in wwiv::bbs::WFC::doWFCEvents (this=0x7fffffffd950)         at /bbs/git/wwiv/bbs/wfc.cpp:296                                            
#4  0x000055555575e811 in Application::GetCaller (this=0x555555e43080)
    at /bbs/git/wwiv/bbs/application.cpp:599
#5  0x0000555555760217 in Application::Run (this=0x555555e43080, argc=1,
    argv=0x7fffffffed18) at /bbs/git/wwiv/bbs/application.cpp:961
#6  0x000055555575a4e2 in bbsmain (argc=1, argv=0x7fffffffed18)
    at /bbs/git/wwiv/bbs/bbs.cpp:91
#7  0x000055555575a3f0 in main (argc=1, argv=0x7fffffffed18)
    at /bbs/git/wwiv/bbs/bbs_main.cpp:22
(gdb)
```

**Comment by BloodStoneBBS** [comment]
Similar here on Windows 7 w32:
All I have though is this: 
Unhandled exception at 0x014068E8 in bbs.exe: 0xC0000094: Integer division by zero.

**Comment by granitepenguin** [comment]
my callout.nets

WWIVnet
@1 && /15
@91 && +

rushnet
@1 && /120
