### ISSUE TITLE
bbs segfault

### ISSUE THREAD

**Issue by granitepenguin** [wwivbbs/wwiv#1145]
OS: debian 9
WWIV: 2846

latest build segfault

```gdb
(gdb) run
Starting program: /bbs/wwiv/bbs
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff75180c0 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::empty() const ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
(gdb) bt
#0  0x00007ffff75180c0 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::empty() const ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#1  0x0000555555a0b80d in wwiv::core::FilePath (
    dirname=<error reading variable: Cannot access memory at address 0x18>,
    filename="user.lst") at /bbs/git/wwiv/core/file.cpp:116
#2  0x0000555555a054fb in wwiv::sdk::UserManager::readuser_nocache (this=0x0,
    pUser=0x555555eb5e68, user_number=1)
    at /bbs/git/wwiv/sdk/usermanager.cpp:82
#3  0x0000555555a056f7 in wwiv::sdk::UserManager::readuser (this=0x0,
    pUser=0x555555eb5e68, user_number=1)
    at /bbs/git/wwiv/sdk/usermanager.cpp:104
#4  0x0000555555791c9c in Application::ReadCurrentUser (this=0x555555eb58e0,
    user_number=1) at /bbs/git/wwiv/bbs/application.cpp:181
#5  0x00005555557c8ab2 in wwiv::bbs::SessionContext::reset (
    this=0x555555eb6300) at /bbs/git/wwiv/bbs/context.cpp:42
#6  0x00005555557c896e in wwiv::bbs::SessionContext::SessionContext (
    this=0x555555eb6300, a=0x555555eb58e0) at /bbs/git/wwiv/bbs/context.cpp:28
#7  0x0000555555790aad in Application::Application (this=0x555555eb58e0,
    localIO=0x555555eb4a40) at /bbs/git/wwiv/bbs/application.cpp:100
#8  0x000055555578fb1a in CreateSession (localIO=0x555555eb4a40)
    at /bbs/git/wwiv/bbs/bbs.cpp:76
#9  0x000055555578fbaa in bbsmain (argc=1, argv=0x7fffffffecd8)
    at /bbs/git/wwiv/bbs/bbs.cpp:90
#10 0x000055555578fae0 in main (argc=1, argv=0x7fffffffecd8)
    at /bbs/git/wwiv/bbs/bbs_main.cpp:22
```

**Comment by granitepenguin** [comment]
Fixed in https://github.com/wwivbbs/wwiv/compare/77d30ef61b65...6085ed2e4076
