### ISSUE TITLE
wwivutil print segfaults

### ISSUE THREAD

**Issue by granitepenguin** [wwivbbs/wwiv#1149]
OS: Debian 9 64bit
WWIV: 2859

testing the new print function of wwivutil.  Getting a segfault 

```gdb
gdb --args ./wwivutil print gfiles/welcome.ans

Program received signal SIGSEGV, Segmentation fault.                                                                                0x000055555577d65e in wwiv::dk::ansi::Ansi::write_in_sequence (                                                 this=0x7fffffffc670, c=65 'A') at /bbs/git/wwiv/sdk/ansi/ansi.cpp:79        
79          b_->gotoxy(b_->x(), std::max(0, b_->y() - ns[0]));
                  (gdb) bt                                                                        
#0  0x000055555577d65e in wwiv::sdk::ansi::Ansi::write_in_sequence (
                this=0x7fffffffc670, c=65 'A') at /bbs/git/wwiv/sdk/ansi/ansi.cpp:79        
#1  0x000055555577d2e3 in wwiv::sdk::ansi::Ansi::write (this=0x7fffffffc670,
        c=65 'A') at /bbs/git/wwiv/sdk/ansi/ansi.cpp:44                             
#2  0x000055555574ba87 in wwiv::wwivutil::PrintCommand::Execute (
                   this=0x555555ab8970) at /bbs/git/wwiv/wwivutil/print/print.cpp:82           
#3  0x000055555575099e in wwiv::core::CommandLineCommand::Execute (
                 this=0x7fffffffe9f8) at /bbs/git/wwiv/core/command_line.cpp:251             
#4  0x000055555574f344 in wwiv::core::CommandLine::Execute (
                        this=0x7fffffffe9f8) at /bbs/git/wwiv/core/command_line.cpp:108             
#5  0x000055555571049b in wwiv::wwivutil::WWIVUtil::Main (this=0x7fffffffe9e0)
      at /bbs/git/wwiv/wwivutil/wwivutil.cpp:88                                   
#6  0x000055555570efe6 in main (argc=3, argv=0x7fffffffec58)
                        at /bbs/git/wwiv/wwivutil/wwivutil.cpp:119                                  
(gdb)
```

**Comment by wwiv** [comment]
Can you attach the ansi too?

**Comment by granitepenguin** [comment]
[welcome.ans.zip](https://github.com/wwivbbs/wwiv/files/2283985/welcome.ans.zip)
