### ISSUE TITLE
bbs binary crash on not enough instances

### ISSUE THREAD

**Issue by granitepenguin** [wwivbbs/wwiv#1473]
Looks like an index problem.  The bbs command is getting a SIGABRT because of trying to use an instance higher than what's allowed in wwivconfig.  Maybe test this before starting bbs binary and cleanly exit?

```log
/var/log/syslog:Dec 10 19:40:10 beaglebbs wwivd[10946]: 2021-12-10 19:40:10,683 VER-2 BBS is: WWIV
/var/log/syslog:Dec 10 19:40:10 beaglebbs wwivd[10946]: 2021-12-10 19:40:10,684 VER-1 [10946] launching node(5)
/var/log/syslog:Dec 10 19:40:10 beaglebbs wwivd[10946]: 2021-12-10 19:40:10,684 VER-2 SemaphoreFile::try_acquire: '"/bbs/wwiv/data/nodeinuse.5"'
/var/log/syslog:Dec 10 19:40:10 beaglebbs wwivd[10946]: 2021-12-10 19:40:10,685 VER-2 Setting blocking mode.
/var/log/syslog:Dec 10 19:40:10 beaglebbs wwivd[10946]: 2021-12-10 19:40:10,685 VER-2 raw_cmd: ./bbs -XT -H@H -N@N
/var/log/syslog:Dec 10 19:40:10 beaglebbs wwivd[10946]: 2021-12-10 19:40:10,686 VER-2 [10946] Invoking Command Line (posix_spawn):./bbs -XT -H7 -N5
/var/log/syslog:Dec 10 19:40:10 beaglebbs wwivd[10946]: 2021-12-10 19:40:10,688 VER-2 after posix_spawn; ret: 0
/var/log/syslog:Dec 10 19:40:10 beaglebbs wwivd[10946]: 2021-12-10 19:40:10,688 VER-2 [10946] before waitpid
/var/log/syslog:Dec 10 19:40:10 beaglebbs wwivd[10946]: 2021-12-10 19:40:10,704 ERROR Not enough instances configured in wwivconfig. Currently: 4
/var/log/syslog:Dec 10 19:40:10 beaglebbs wwivd[10946]: 2021-12-10 19:40:10,705 FATAL Failed Precondition: at ../bbs/application.cpp:1326 Condition: instances_
/var/log/syslog:Dec 10 19:40:10 beaglebbs wwivd[10946]: Aborted (core dumped)
```

```gdb
Reading symbols from /bbs/wwiv/bbs...done.
[New LWP 20267]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `./bbs -XT -H7 -N5'.
Program terminated with signal SIGABRT, Aborted.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007faf81460535 in __GI_abort () at abort.c:79
#2  0x0000560972bf605a in wwiv::core::Logger::~Logger (this=0x7ffd327eb370, __in_chrg=<optimized out>) at ../core/log.cpp:133
#3  0x00005609726a77eb in Application::instances (this=0x560973ff28c0) at ../bbs/application.cpp:1326
#4  0x000056097271c9b0 in write_inst (loc=0, subloc=0, flags=0) at ../bbs/instmsg.cpp:161
#5  0x00005609726a1df2 in Application::ExitBBSImpl (this=0x560973ff28c0, exit_level=1, perform_shutdown=true)
    at ../bbs/application.cpp:801
#6  0x000056097269b005 in bbsmain (argc=4, argv=0x7ffd327ec3b8) at ../bbs/bbs.cpp:78
#7  0x000056097269ae05 in main (argc=4, argv=0x7ffd327ec3b8) at ../bbs/bbs_main.cpp:22
```

**Comment by wwiv** [comment]
reproduced with a debug build on windows too

```
2021-12-12 08:15:18,321 ERROR Not enough instances configured in wwivconfig. Currently: 4
2021-12-12 08:15:18,944 FATAL Failed Precondition: at W:\wwiv\bbs\application.cpp:1326 Condition: instances_ 11: Application::instances = 9e4180 (W:\wwiv\bbs\application.cpp: 1326)
10: write_inst = a9da00 (W:\wwiv\bbs\instmsg.cpp: 161)
9: Application::ExitBBSImpl = 9e7b40 (W:\wwiv\bbs\application.cpp: 801)
8: bbsmain = 9d9760 (W:\wwiv\bbs\bbs.cpp: 78)
7: main = 9d9670 (W:\wwiv\bbs\bbs_main.cpp: 22)
6: invoke_main = 1018470 (d:\a01\_work\11\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl: 78)
5: __scrt_common_main_seh = 10181a0 (d:\a01\_work\11\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl: 288)
4: __scrt_common_main = 1018180 (d:\a01\_work\11\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl: 331)
3: mainCRTStartup = 1018520 (d:\a01\_work\11\s\src\vctools\crt\vcstartup\src\startup\exe_main.cpp: 17)
2: BaseThreadInitThunk = 7604fa10
1: RtlGetAppContainerNamedObjectPath = 77487980
0: RtlGetAppContainerNamedObjectPath = 77487980
```
