### ISSUE TITLE
network2 segfault during processing

### ISSUE THREAD

**Issue by granitepenguin** [wwivbbs/wwiv#768]
OS: Linux
Build: 

./bbs is getting into an endless loop because network2 is segfaulting while processing local.net

Starting program: /bbs/wwiv/network2 .0
I20160717:150341 network2 version 5.1.0.development (Jul  8 2016, 23:57:28)
I20160717:150341 network2 starting at Sun Jul 17 15:03:41 2016
I20160717:150341 NETWORK2 for network: WWIVnet
I20160717:150341 Processing: nets/wwivnet/local.net
I20160717:150341 Processing message with type: main_type_ssm/0
I20160717:150341 ==============================================================
I20160717:150341   Receiving SSM for user: #1
I20160717:150341     + SSM  'WWIVnet: Granitepenguin #95 @1 (David) read your mail on 07/17/16'
I20160717:150341 ==============================================================
I20160717:150341 Processing message with type: main_type_new_post/0
I20160717:150341 ==============================================================
I20160717:150341   Processing New Post on subtype: WWIVSYS
I20160717:150341   title:   last one
I20160717:150341   sender:  solaris (11:1/210)@8304.WWIVnet-FTN
I20160717:150341   date:    Sun Jul 17 14:48:09 2016

Program received signal SIGSEGV, Segmentation fault.
0x00000000004770cc in std::unique_ptr<wwiv::sdk::msgapi::WWIVMessageHeader, std::default_delete<wwiv::sdk::msgapi::WWIVMessageHeader> >::get (this=0x8)
    at /usr/include/c++/4.9/bits/unique_ptr.h:305
305           { return std::get<0>(_M_t); }
(gdb) bt
#0  0x00000000004770cc in std::unique_ptr<wwiv::sdk::msgapi::WWIVMessageHeader, std::default_delete<wwiv::sdk::msgapi::WWIVMessageHeader> >::get (this=0x8)

```
at /usr/include/c++/4.9/bits/unique_ptr.h:305
```
#1  0x00000000004771c0 in std::unique_ptr<wwiv::sdk::msgapi::WWIVMessageHeader, std::default_delete<wwiv::sdk::msgapi::WWIVMessageHeader> >::release (this=0x8)

```
at /usr/include/c++/4.9/bits/unique_ptr.h:327
```
#2  0x0000000000476f4e in wwiv::sdk::msgapi::WWIVMessage::release_header (this=

```
0x0) at /bbs/build/wwiv/sdk/../sdk/msgapi/message_wwiv.h:113
```
#3  0x00000000004764be in wwiv::sdk::msgapi::WWIVMessageArea::ReadMessageHeader

```
(this=0x6a23c0, message_number=1190)
at /bbs/build/wwiv/sdk/msgapi/message_area_wwiv.cpp:211
```
#4  0x000000000045c03c in wwiv::net::network2::handle_post (context=...,

```
nh=..., list=std::vector of length 0, capacity 0,
raw_text="WWIVSYS\000last one\000solaris (11:1/210)@8304.WWIVnet-FTN\r\nSun Jul 17 14:48:09 2016\r\n\004\060R 38RC6 - 07/17/16 14:49:32 WWIVnet ->1\r\n\003\061To\003\071.......... \003\062All\r\n\r\n\004\060MSGID: 11:1/210 00debc2c\r\n\004\060TZUTC: -0400\r\nbinkp s"...) at /bbs/build/wwiv/network2/post.cpp:161
```
#5  0x0000000000451940 in handle_packet (context=..., nh=...,

```
list=std::vector of length 0, capacity 0,
text="WWIVSYS\000last one\000solaris (11:1/210)@8304.WWIVnet-FTN\r\nSun Jul 17 14:48:09 2016\r\n\004\060R 38RC6 - 07/17/16 14:49:32 WWIVnet ->1\r\n\003\061To\003\071.......... \003\062All\r\n\r\n\004\060MSGID: 11:1/210 00debc2c\r\n\004\060TZUTC: -0400\r\nbinkp s"...) at /bbs/build/wwiv/network2/network2.cpp:179
```
#6  0x0000000000451e92 in handle_file (context=..., name="local.net")

```
at /bbs/build/wwiv/network2/network2.cpp:253
```
#7  0x0000000000453237 in main (argc=2, argv=0x7fffffffe708)

```
at /bbs/build/wwiv/network2/network2.cpp:350
```

**Comment by granitepenguin** [comment]
Got a little further, but still crashing

``` gdb
wwiv@vps40748:~$ gdb network2
GNU gdb (Debian 7.7.1+dfsg-5) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from network2...done.
(gdb) r .0
Starting program: /bbs/wwiv/network2 .0
I20160717:155458 network2 version 5.1.0.1996 (Jul 17 2016, 15:50:34)
I20160717:155458 network2 starting at Sun Jul 17 15:54:58 2016
I20160717:155458 NETWORK2 for network: WWIVnet
I20160717:155458 Processing: nets/wwivnet/local.net
I20160717:155458 Processing message with type: main_type_ssm/0
I20160717:155458 ==============================================================
I20160717:155458   Receiving SSM for user: #1
I20160717:155458     + SSM  'WWIVnet: Granitepenguin #95 @1 (David) read your mail on 07/17/16'
I20160717:155458 ==============================================================
I20160717:155458 Processing message with type: main_type_new_post/0
I20160717:155458 ==============================================================
I20160717:155458   Processing New Post on subtype: WWIVSYS
I20160717:155458   Title:   last one
I20160717:155458   Sender:  solaris (11:1/210)@8304.WWIVnet-FTN
I20160717:155458   Date:    Sun Jul 17 14:48:09 2016
I20160717:155458 num_messages=1161
I20160717:155458     + Posted  'last one'
I20160717:155458 ==============================================================
I20160717:155458 Processing message with type: main_type_new_post/0
I20160717:155458 ==============================================================
I20160717:155458   Processing New Post on subtype: WWIVDEV
I20160717:155458   Title:   Re: Running network1
I20160717:155458   Sender:  Patch (11:1/212)@8304.WWIVnet-FTN
I20160717:155458   Date:    Sun Jul 17 08:37:56 2016
I20160717:155458 num_messages=827

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7b9126b in std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(std::string const&) ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
(gdb) bt
#0  0x00007ffff7b9126b in std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(std::string const&) ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#1  0x000000000046e8d8 in wwiv::strings::StringTrim (
    orig=<error reading variable: Cannot access memory at address 0xffff00070006ffe7>) at /bbs/build/wwiv/core/strings.cpp:289
#2  0x0000000000475b83 in wwiv::sdk::msgapi::WWIVMessageArea::ReadMessage (
    this=0x6a23d0, message_number=616)
    at /bbs/build/wwiv/sdk/msgapi/message_area_wwiv.cpp:168
#3  0x000000000047645e in wwiv::sdk::msgapi::WWIVMessageArea::ReadMessageHeader
    (this=0x6a23d0, message_number=616)
    at /bbs/build/wwiv/sdk/msgapi/message_area_wwiv.cpp:210
#4  0x000000000045c046 in wwiv::net::network2::handle_post (context=...,
    nh=..., list=std::vector of length 0, capacity 0,
    raw_text="WWIVDEV\000Re: Running network1\000Patch (11:1/212)@8304.WWIVnet-FTN\r\nSun Jul 17 08:37:56 2016\r\n\004\060R 38RC6 - 07/17/16 14:59:16 WWIVnet ->1\r\n\003\061To\003\071.......... \003\062Weatherman\r\n\r\n\004\060MSGID: 11:1/212 48f144bc\r\n\004\060REPL"...) at /bbs/build/wwiv/network2/post.cpp:162
#5  0x0000000000451890 in handle_packet (context=..., nh=...,
    list=std::vector of length 0, capacity 0,
    text="WWIVDEV\000Re: Running network1\000Patch (11:1/212)@8304.WWIVnet-FTN\r\nSun Jul 17 08:37:56 2016\r\n\004\060R 38RC6 - 07/17/16 14:59:16 WWIVnet ->1\r\n\003\061To\003\071.......... \003\062Weatherman\r\n\r\n\004\060MSGID: 11:1/212 48f144bc\r\n\004\060REPL"...) at /bbs/build/wwiv/network2/network2.cpp:179
#6  0x0000000000451de2 in handle_file (context=..., name="local.net")
    at /bbs/build/wwiv/network2/network2.cpp:271
#7  0x0000000000453187 in main (argc=2, argv=0x7fffffffe708)
    at /bbs/build/wwiv/network2/network2.cpp:368
```

**Comment by granitepenguin** [comment]
Here's a sample local.net that the system is barfing on

[local.net.txt](https://github.com/wwivbbs/wwiv/files/368149/local.net.txt)

**Comment by granitepenguin** [comment]
Sample sub files that also segfault on the wwivutil

[wwivdev-segfault.zip](https://github.com/wwivbbs/wwiv/files/368164/wwivdev-segfault.zip)

**Comment by wwiv** [comment]
possibly fixed with https://github.com/wwivbbs/wwiv/commit/cbf15712b8faebdb96a0b0f227a872775454fa50

**Comment by granitepenguin** [comment]
Here's the sample wwivsys
[wwivsys-gp.zip](https://github.com/wwivbbs/wwiv/files/368302/wwivsys-gp.zip)
