### ISSUE TITLE
ExceptionSystem.ObjectDisposedException: Cannot access a disposed object.

### ISSUE THREAD

**Issue by wwiv** [wwivbbs/wwiv#838]
ExceptionSystem.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.
   at System.Net.Sockets.Socket.Send(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, SocketError& errorCode)
   at System.Net.Sockets.Socket.Send(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   at System.Net.Sockets.Socket.Send(Byte[] buffer)
   at WWIV5TelnetServer.SocketServer.send(Socket socket, String s)
   at WWIV5TelnetServer.SocketServer.SendBusyAndCloseSocket(Socket socket)
   at WWIV5TelnetServer.SocketServer.Run()

**Comment by wwiv** [comment]
fixed in https://github.com/wwivbbs/wwiv/commit/f312bb18bfea36103d0e3c55d1664016d26f5d58
