### ISSUE TITLE
network2 hanging while processing local.net

### ISSUE THREAD

**Issue by granitepenguin** [wwivbbs/wwiv#853]
OS linux
Build 5.2.0.2146

When network2 runs, it gets to a point and hangs.  Here's some bt info (but I don't have any debug details yet)

``` gdb
Starting program: /bbs/wwiv/network2 .0 --v=2
2016-10-03 10:36:14,257 INFO   NETWORK2 for network: WWIVnet
2016-10-03 10:36:14,258 INFO   Processing: nets/wwivnet/local.net
2016-10-03 10:36:14,258 INFO   Processing message with type: main_type_new_post/0
2016-10-03 10:36:14,258 VER-1 ==============================================================
2016-10-03 10:36:14,259 VER-1   Processing New Post on subtype: WEATHER
2016-10-03 10:36:14,259 VER-1   Title:   Today's Weather History
2016-10-03 10:36:14,259 VER-1   Sender:  Daryl Stout (11:1/214)@8304.WWIVnet-FTN
2016-10-03 10:36:14,259 VER-1   Date:    Mon Oct 03 00:01:40 2016
^C
Program received signal SIGINT, Interrupt.
0x00007ffff72eb2c7 in flock () at ../sysdeps/unix/syscall-template.S:81
81      ../sysdeps/unix/syscall-template.S: No such file or directory.
(gdb) bt
#0  0x00007ffff72eb2c7 in flock () at ../sysdeps/unix/syscall-template.S:81
#1  0x00000000004e6fa8 in File::Open(int, int) ()
#2  0x0000000000504c6d in wwiv::core::DataFile<postrec, 100ul>::DataFile(std::string const&, int, int) ()
#3  0x00000000005026f1 in wwiv::sdk::msgapi::WWIVMessageArea::WWIVMessageArea(wwiv::sdk::msgapi::WWIVMessageApi*, std::string const&, std::string const&) ()
#4  0x0000000000501b0f in wwiv::sdk::msgapi::WWIVMessageApi::Open(std::string const&) ()
#5  0x00000000004cc518 in wwiv::net::network2::handle_post(wwiv::net::network2::Context&, wwiv::net::Packet&) ()
#6  0x00000000004abdfb in handle_packet(wwiv::net::network2::Context&, wwiv::net::Packet&) ()
#7  0x00000000004ac37d in handle_file(wwiv::net::network2::Context&, std::string const&) ()
#8  0x00000000004acb7a in main ()
(gdb) quit
```

**Comment by granitepenguin** [comment]
``` gdb
Starting program: /bbs/wwiv/network2 .0 --v=3
2016-10-03 12:30:18,792 VER-3 SH_OPEN /bbs/wwiv/config.dat, access=0
2016-10-03 12:30:18,793 VER-3 SH_OPEN /bbs/wwiv/config.dat, access=0, handle=4
2016-10-03 12:30:18,793 VER-3 SH_OPEN /bbs/wwiv/data/networks.dat, access=0
2016-10-03 12:30:18,793 VER-3 SH_OPEN /bbs/wwiv/data/networks.dat, access=0, handle=4
2016-10-03 12:30:18,793 INFO   NETWORK2 for network: WWIVnet
2016-10-03 12:30:18,793 VER-3 SH_OPEN /bbs/wwiv/data/subs.dat, access=2
2016-10-03 12:30:18,793 VER-3 SH_OPEN /bbs/wwiv/data/subs.dat, access=2, handle=4
2016-10-03 12:30:18,794 INFO   Processing: nets/wwivnet/local.net
2016-10-03 12:30:18,795 VER-3 SH_OPEN nets/wwivnet/local.net, access=0
2016-10-03 12:30:18,795 VER-3 SH_OPEN nets/wwivnet/local.net, access=0, handle=4
2016-10-03 12:30:18,795 INFO   Processing message with type: main_type_new_post/0
2016-10-03 12:30:18,795 VER-1 ==============================================================2016-10-03 12:30:18,795 VER-1   Processing New Post on subtype: WEATHER
2016-10-03 12:30:18,795 VER-1   Title:   Today's Weather History
2016-10-03 12:30:18,795 VER-1   Sender:  Daryl Stout (11:1/214)@8304.WWIVnet-FTN
2016-10-03 12:30:18,795 VER-1   Date:    Mon Oct 03 00:01:40 2016
2016-10-03 12:30:18,795 VER-3 SH_OPEN /bbs/wwiv/data/weather.sub, access=0
2016-10-03 12:30:18,795 VER-3 SH_OPEN /bbs/wwiv/data/weather.sub, access=0, handle=5
2016-10-03 12:30:18,796 VER-3 SH_OPEN /bbs/wwiv/msgs/weather.dat, access=0
2016-10-03 12:30:18,796 VER-3 SH_OPEN /bbs/wwiv/msgs/weather.dat, access=0, handle=6
2016-10-03 12:30:18,796 VER-3 SH_OPEN /bbs/wwiv/data/weather.sub, access=0
2016-10-03 12:30:18,796 VER-3 SH_OPEN /bbs/wwiv/data/weather.sub, access=0, handle=7

```
