### ISSUE TITLE
bbs binary segfaults on exit

### ISSUE THREAD

**Issue by granitepenguin** [wwivbbs/wwiv#854]
OS: Linux
Version: 5.2.0.2153

When exiting the bbs, the binary segfaults.
WWIV Bulletin Board System 5.2.0.development exiting at error level 2

I get the same thing whether I am using login via WFC or over telnet

``` gdb
Program received signal SIGSEGV, Segmentation fault.
0x00000000006f9270 in std::_Rb_tree<std::string, std::pair<std::string const, int>, std::_Select1st<std::pair<std::string const, int> >, std::less<std::string>, std::allocator<std::pair<std::string const, int> > >::empty (this=0x18)
    at /usr/include/c++/4.9/bits/stl_tree.h:768
768           { return _M_impl._M_node_count == 0; }
(gdb) bt
#0  0x00000000006f9270 in std::_Rb_tree<std::string, std::pair<std::string const, int>, std::_Select1st<std::pair<std::string const, int> >, std::less<std::string>, std::allocator<std::pair<std::string const, int> > >::empty (this=0x18)
    at /usr/include/c++/4.9/bits/stl_tree.h:768
#1  0x00000000006f8e08 in std::map<std::string, int, std::less<std::string>, std::allocator<std::pair<std::string const, int> > >::empty (this=0x18)
    at /usr/include/c++/4.9/bits/stl_map.h:465
#2  0x00000000006f8bde in el::base::VRegistry::allowed (this=0x0, vlevel=3,
    file=0x8d5e3c "/bbs/build/wwiv/core/file.cpp")
    at /bbs/build/wwiv/bbs/../deps/easylogging/easylogging++.h:3832
#3  0x0000000000768d35 in File::~File (this=0xc07020 <qscanFile>,
    __in_chrg=<optimized out>) at /bbs/build/wwiv/core/file.cpp:127
#4  0x00007ffff69cab29 in __run_exit_handlers (status=2,
    listp=0x7ffff6d385a8 <__exit_funcs>,
    run_list_atexit=run_list_atexit@entry=true) at exit.c:82
#5  0x00007ffff69cab75 in __GI_exit (status=<optimized out>) at exit.c:104
#6  0x00000000005ae2ad in WSession::ExitBBSImpl (this=0xc16650, exit_level=2,
    perform_shutdown=true) at /bbs/build/wwiv/bbs/wsession.cpp:1076
#7  0x00000000005ae04a in WSession::QuitBBS (this=0xc16650)
    at /bbs/build/wwiv/bbs/wsession.cpp:1052
#8  0x00000000005ad335 in WSession::doWFCEvents (this=0xc16650)
    at /bbs/build/wwiv/bbs/wsession.cpp:845
#9  0x00000000005ac72f in WSession::GetCaller (this=0xc16650)
    at /bbs/build/wwiv/bbs/wsession.cpp:585
---Type <return> to continue, or q <return> to quit---
#10 0x00000000005af6c5 in WSession::Run (this=0xc16650, argc=1,
    argv=0x7fffffffe728) at /bbs/build/wwiv/bbs/wsession.cpp:1377
#11 0x0000000000590b29 in WApplication::BBSMainLoop (this=0xc101c0, argc=1,
    argv=0x7fffffffe728) at /bbs/build/wwiv/bbs/bbs.cpp:81
#12 0x0000000000590d00 in bbsmain (argc=1, argv=0x7fffffffe728)
    at /bbs/build/wwiv/bbs/bbs.cpp:110
#13 0x00000000005905c6 in main (argc=1, argv=0x7fffffffe728)
    at /bbs/build/wwiv/bbs/bbs_main.cpp:22
```

**Comment by wwiv** [comment]
fixed in https://github.com/wwivbbs/wwiv/commit/11a1bb5c3c5e8e554333a3e94c453ff08e28cef5
