### ISSUE TITLE
local e-mail message crashes network2 

### ISSUE THREAD

**Issue by BloodStoneBBS** [wwivbbs/wwiv#982]
OS: Windows 7 
Ver 5 Build 5.3.2456

Found network2 crashed repeatedly when trying to process local e-mail.
Upgraded to 5.3.2459 - still crashing, Downgraded to 5.3.2443, still crashing.
Removed local.net - tested local e-mail and network2 and it worked.
Replaced local.net - tested network2 - Crashed.

Network2 crashing just after subject.
The message indicates that there may also be an additional issue with 5.3.2459 in the door game arena.

Zipped Local.net
[local.zip](https://github.com/wwivbbs/wwiv/files/705336/local.zip)

**Comment by BloodStoneBBS** [comment]
Correction: E-mail originated from node 255. 

Update:

Replicated on 2443. Sent network e-mail from node 255 to 1@707.
Network2 crashing on processing local.net
![capture](https://cloud.githubusercontent.com/assets/13243281/21948470/5e839aee-d9a0-11e6-920a-9e92bbd7adc9.PNG)

**Comment by BloodStoneBBS** [comment]
The above  instance prevented a message from reaching the Net test sub as well.

Then I somehow lost the local.net when I cleared the e-mail message and then dragged the file into the \networks\wwiv folder. Looking for it now.

Update. found the local.net, moved it back and tossed. The message successfully reached the SUB.

**Comment by granitepenguin** [comment]
I'm seeing the same thing here.  my local.net has an email reply from Mark that trashed me.  Working on getting a debug symbol bt, but here's what I have so far.


```gdb
(gdb) run
Starting program: /bbs/wwiv/network2 .0
2017-01-13 19:08:47,776 INFO  NETWORK2 for network: WWIVnet
2017-01-13 19:08:47,779 INFO  Processing: nets/wwivnet/local.net
2017-01-13 19:08:47,781 INFO  Processing message with type: main_type_email/0
2017-01-13 19:08:47,781 INFO  ==============================================================
2017-01-13 19:08:47,781 INFO  Processing email to user #1
2017-01-13 19:08:47,781 INFO    Title: 'Re: subs not passing?'

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7b66f10 in std::basic_ostream<char, std::char_traits<char> >& std::operator<< <char, std::char_traits<char>, std::allocator<char> >(std::basic_ostream<char, std::char_traits<char> >&, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
(gdb) bt
#0  0x00007ffff7b66f10 in std::basic_ostream<char, std::char_traits<char> >& std::operator<< <char, std::char_traits<char>, std::allocator<char> >(std::basic_ostream<char, std::char_traits<char> >&, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#1  0x0000000000547e42 in File::SetName(std::string const&, std::string const&)
    ()
#2  0x000000000054719a in File::File(std::string const&, std::string const&) ()
#3  0x0000000000566597 in wwiv::sdk::msgapi::WWIVMessageApi::OpenEmail() ()
#4  0x0000000000528c86 in wwiv::net::network2::handle_email(wwiv::net::network2::Context&, unsigned short, wwiv::net::Packet&) ()
#5  0x000000000050a17a in handle_packet(wwiv::net::network2::Context&, wwiv::net::Packet&) ()
#6  0x000000000050a702 in handle_file(wwiv::net::network2::Context&, std::string const&) ()
#7  0x000000000050ada0 in main ()
(gdb) quit
```

**Comment by granitepenguin** [comment]
Here's a bt with symbols

```gdb
Reading symbols from ./network2...done.
(gdb) set args .0
(gdb) run
Starting program: /bbs/wwiv/network2 .0
2017-01-13 20:18:01,940 INFO  NETWORK2 for network: WWIVnet
2017-01-13 20:18:01,943 INFO  Processing: nets/wwivnet/local.net
2017-01-13 20:18:01,943 INFO  Processing message with type: main_type_email/0
2017-01-13 20:18:01,943 INFO  ==============================================================
2017-01-13 20:18:01,944 INFO  Processing email to user #1
2017-01-13 20:18:01,944 INFO    Title: 'Re: subs not passing?'

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7b66f10 in std::basic_ostream<char, std::char_traits<char> >& std::operator<< <char, 
std::char_traits<char>, std::allocator<char> >(std::basic_ostream<char, std::char_traits<char> >&, 
std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
(gdb) bt
#0  0x00007ffff7b66f10 in std::basic_ostream<char, std::char_traits<char> >& std
::operator<< <char, std::char_traits<char>, std::allocator<char> >(std::basic_os
tream<char, std::char_traits<char> >&, std::basic_string<char, std::char_traits<
char>, std::allocator<char> > const&) ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#1  0x0000000000547e42 in File::SetName (this=0x7fffffffd340,
    dirname=<error reading variable: Cannot access memory at address 0x18>,
    filename="email.dat") at /bbs/build/wwiv/core/file.cpp:215
#2  0x000000000054719a in File::File (this=0x7fffffffd340,
    dir=<error reading variable: Cannot access memory at address 0x18>,
    filename="email.dat") at /bbs/build/wwiv/core/file.cpp:137
#3  0x0000000000566597 in wwiv::sdk::msgapi::WWIVMessageApi::OpenEmail (
    this=0x0) at /bbs/build/wwiv/sdk/msgapi/message_api_wwiv.cpp:185
#4  0x0000000000528c86 in wwiv::net::network2::handle_email (context=...,
    to_user=1, p=...) at /bbs/build/wwiv/network2/email.cpp:159
#5  0x000000000050a17a in handle_packet (context=..., p=...)
    at /bbs/build/wwiv/network2/network2.cpp:197
#6  0x000000000050a702 in handle_file (context=..., name="local.net")
    at /bbs/build/wwiv/network2/network2.cpp:279
#7  0x000000000050ada0 in main (argc=2, argv=0x7fffffffe708)
    at /bbs/build/wwiv/network2/network2.cpp:324
(gdb)
```

and the [local.net.zip](https://github.com/wwivbbs/wwiv/files/705700/local.net.zip) that goes with it
